platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Capacitor core and plugins from CocoaPods repository
  pod 'Capacitor', '~> 6.0'
  pod 'CapacitorCordova', '~> 6.0'
  pod 'CapacitorApp', '~> 6.0'
  pod 'CapacitorCamera', '~> 6.0'
  pod 'CapacitorFilesystem', '~> 6.0'
  pod 'CapacitorHaptics', '~> 6.0'
  pod 'CapacitorPushNotifications', '~> 6.0'
  pod 'CapacitorStatusBar', '~> 6.0'
  pod 'CapacitorToast', '~> 6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
