-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+zYtbjAtrXXn17U3
oeCov4F7lcnl0mXRK+QOmX3C+7mgCgYIKoZIzj0DAQehRANCAASM84tqcvBnxJtq
yxlGQLCnzYsrtPPE1qLIfOfkiE2wPNpxw2vcTTg7C/aPHqiRqcEAADyjhrG3sVEP
AzzsELD4
-----END PRIVATE KEY-----