platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  pod 'Capacitor', '6.1.2'
  pod 'CapacitorCordova', '6.1.2'
  pod 'CapacitorApp', '6.0.1'
  pod 'CapacitorCamera', '6.0.2'
  pod 'CapacitorFilesystem', '6.0.1'
  pod 'CapacitorHaptics', '6.0.1'
  pod 'CapacitorPushNotifications', '6.0.2'
  pod 'CapacitorStatusBar', '6.0.1'
  pod 'CapacitorToast', '6.0.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end